version: '3'

services:
  redmine:
    image: redmine:4.2.1
    restart: always
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: ${POSTGRESS_PASSWORD}
    ports:
      - "8080:3000"
    volumes:
      - redmine_data:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  redmine_data:
  redmine_plugins:
  postgresql_data:
